socks5_listen: "127.0.0.1:9910"
http_proxy_listen: "127.0.0.1:9911"
pac_listen: "127.0.0.1:9912"
control_listen: "127.0.0.1:9913"
exit_constraint: "auto"
allow_direct: false
port_forward: []
cache: "./TMP/cache/geph5.db"
vpn: false
spoof_dns: false
passthrough_china: false
dry_run: false
credentials:
  secret: "912238511575407778606820"
broker:
  race:
    - fronted:
        front: "https://www.cdn77.com/"
        host: "1826209743.rsc.cdn77.org"
    - fronted:
        front: "https://vuejs.org/"
        host: "svitania-naidallszei-2.netlify.app"
broker_keys:
  master: "88c1d2d4197bed815b01a22cadfc6c35aa246dddb553682037a118aebfaa3954"
  mizaru_free: "0558216cbab7a9c46f298f4c26e171add9af87d0694988b8a8fe52ee932aa754"
  mizaru_plus: "cf6f58868c6d9459b3a63bc2bd86165631b3e916bad7f62b578cd9614e0bcb3b"
  mizaru_bw: ""
